package com.wfzcx.aros.xxtx.po;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * BMsgbaseinfo generated by hbm2java
 */
@Entity
@Table(name = "B_MSGBASEINFO")
public class BMsgbaseinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String caseid;
	private String msgtype;
	private String msgcontent;
	private String gnetime;
	private String ifread;
	private String acptime;
	private String sendfre;
	private String sender;

	public BMsgbaseinfo() {
	}

	public BMsgbaseinfo(String id) {
		this.id = id;
	}

	public BMsgbaseinfo(String id, String caseid, String msgtype,
			String msgcontent, String gnetime, String ifread, String acptime,
			String sendfre, String sender) {
		this.id = id;
		this.caseid = caseid;
		this.msgtype = msgtype;
		this.msgcontent = msgcontent;
		this.gnetime = gnetime;
		this.ifread = ifread;
		this.acptime = acptime;
		this.sendfre = sendfre;
		this.sender = sender;
	}

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "ID")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CASEID", length = 32)
	public String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(String caseid) {
		this.caseid = caseid;
	}

	@Column(name = "MSGTYPE", length = 2)
	public String getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(String msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "MSGCONTENT", length = 500)
	public String getMsgcontent() {
		return this.msgcontent;
	}

	public void setMsgcontent(String msgcontent) {
		this.msgcontent = msgcontent;
	}

	@Column(name = "GNETIME", length = 30)
	public String getGnetime() {
		return this.gnetime;
	}

	public void setGnetime(String gnetime) {
		this.gnetime = gnetime;
	}

	@Column(name = "IFREAD", length = 1)
	public String getIfread() {
		return this.ifread;
	}

	public void setIfread(String ifread) {
		this.ifread = ifread;
	}

	@Column(name = "ACPTIME", length = 30)
	public String getAcptime() {
		return this.acptime;
	}

	public void setAcptime(String acptime) {
		this.acptime = acptime;
	}

	@Column(name = "SENDFRE", length = 2)
	public String getSendfre() {
		return this.sendfre;
	}

	public void setSendfre(String sendfre) {
		this.sendfre = sendfre;
	}

	@Column(name = "SENDER", length = 30)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

}
