package com.wfzcx.aros.xzfy.po;
// Generated 2016-11-17 10:18:30 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * BCasenoticetempinfo generated by hbm2java
 */
@Entity
@Table(name = "B_CASENOTICETEMPINFO")
public class BCasenoticetempinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String tempid;
	private String protype;
	private String noticename;
	private String buildtime;
	private String contents;
	private String operator;
	private String opttime;
	private String type;
	private BigDecimal nodeid;

	public BCasenoticetempinfo() {
	}

	public BCasenoticetempinfo(String tempid) {
		this.tempid = tempid;
	}

	public BCasenoticetempinfo(String tempid, String protype, String noticename, String buildtime, String contents,
			String operator, String opttime, String type, BigDecimal nodeid) {
		this.tempid = tempid;
		this.protype = protype;
		this.noticename = noticename;
		this.buildtime = buildtime;
		this.contents = contents;
		this.operator = operator;
		this.opttime = opttime;
		this.type = type;
		this.nodeid = nodeid;
	}

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "TEMPID", unique = true, nullable = false, length = 32)
	public String getTempid() {
		return this.tempid;
	}

	public void setTempid(String tempid) {
		this.tempid = tempid;
	}

	@Column(name = "PROTYPE", length = 2)
	public String getProtype() {
		return this.protype;
	}

	public void setProtype(String protype) {
		this.protype = protype;
	}

	@Column(name = "NOTICENAME", length = 200)
	public String getNoticename() {
		return this.noticename;
	}

	public void setNoticename(String noticename) {
		this.noticename = noticename;
	}

	@Column(name = "BUILDTIME", length = 20)
	public String getBuildtime() {
		return this.buildtime;
	}

	public void setBuildtime(String buildtime) {
		this.buildtime = buildtime;
	}

	@Column(name = "CONTENTS")
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "OPERATOR", length = 20)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPTTIME", length = 20)
	public String getOpttime() {
		return this.opttime;
	}

	public void setOpttime(String opttime) {
		this.opttime = opttime;
	}
	
	@Column(name = "TYPE", length = 2)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "NODEID", precision = 22, scale = 0)
	public BigDecimal getNodeid() {
		return nodeid;
	}

	public void setNodeid(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}
}
