package com.wfzcx.aros.xzfy.po;
// Generated 2016-12-1 10:29:50 by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * BCasenoticerelainfo generated by hbm2java
 */
@Entity
@Table(name = "B_CASENOTICERELAINFO")
public class BCasenoticerelainfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String tempid;
	private String caseid;
	private String protype;
	private BigDecimal nodeid;
	private String type;
	private String noticename;
	private String noticecode;
	private String contents;
	private String buildtime;
	private String operator;
	private String opttime;

	public BCasenoticerelainfo() {
	}

	public BCasenoticerelainfo(String id) {
		this.id = id;
	}

	public BCasenoticerelainfo(String id, String tempid, String caseid, String protype, BigDecimal nodeid, String type,
			String noticename, String noticecode, String contents, String buildtime, String operator, String opttime) {
		this.id = id;
		this.tempid = tempid;
		this.caseid = caseid;
		this.protype = protype;
		this.nodeid = nodeid;
		this.type = type;
		this.noticename = noticename;
		this.noticecode = noticecode;
		this.contents = contents;
		this.buildtime = buildtime;
		this.operator = operator;
		this.opttime = opttime;
	}

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TEMPID", length = 32)
	public String getTempid() {
		return this.tempid;
	}

	public void setTempid(String tempid) {
		this.tempid = tempid;
	}

	@Column(name = "CASEID", length = 32)
	public String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(String caseid) {
		this.caseid = caseid;
	}

	@Column(name = "PROTYPE", length = 2)
	public String getProtype() {
		return this.protype;
	}

	public void setProtype(String protype) {
		this.protype = protype;
	}

	@Column(name = "NODEID", precision = 22, scale = 0)
	public BigDecimal getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "TYPE", length = 2)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "NOTICENAME", length = 200)
	public String getNoticename() {
		return this.noticename;
	}

	public void setNoticename(String noticename) {
		this.noticename = noticename;
	}

	@Column(name = "NOTICECODE", length = 200)
	public String getNoticecode() {
		return this.noticecode;
	}

	public void setNoticecode(String noticecode) {
		this.noticecode = noticecode;
	}

	@Column(name = "CONTENTS")
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "BUILDTIME", length = 20)
	public String getBuildtime() {
		return this.buildtime;
	}

	public void setBuildtime(String buildtime) {
		this.buildtime = buildtime;
	}

	@Column(name = "OPERATOR", length = 20)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPTTIME", length = 20)
	public String getOpttime() {
		return this.opttime;
	}

	public void setOpttime(String opttime) {
		this.opttime = opttime;
	}

}
