package com.wfzcx.aros.xzfy.po;
// Generated 2016-9-18 14:42:39 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * BTrialbaseinfo generated by hbm2java
 */
@Entity
@Table(name = "B_TRIALBASEINFO")
public class BTrialbaseinfo implements java.io.Serializable {

	private String trialid;
	private String caseid;
	private String trialtype;
	private String htype;
	private String moderator;
	private String trialtime;
	private String trialplace;
	private String recorder;
	private String joiner;
	private String matters;
	private String contents;
	private String annex;
	private String operator;
	private String opttime;
	private String trialman;
	private BigDecimal userid;


	public BTrialbaseinfo() {
	}

	public BTrialbaseinfo(String trialid) {
		this.trialid = trialid;
	}

	public BTrialbaseinfo(String trialid, String caseid, String trialtype, String htype, String moderator,
			String trialtime, String trialplace, String recorder, String joiner, String matters, String contents,
			String annex, String operator, String opttime, BigDecimal userid, String trialman) {
		this.trialid = trialid;
		this.caseid = caseid;
		this.trialtype = trialtype;
		this.htype = htype;
		this.moderator = moderator;
		this.trialtime = trialtime;
		this.trialplace = trialplace;
		this.recorder = recorder;
		this.joiner = joiner;
		this.matters = matters;
		this.contents = contents;
		this.annex = annex;
		this.operator = operator;
		this.opttime = opttime;
		this.trialman = trialman;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")	
	@Column(name = "TRIALID", unique = true, nullable = false, length = 32)
	public String getTrialid() {
		return this.trialid;
	}

	public void setTrialid(String trialid) {
		this.trialid = trialid;
	}

	@Column(name = "CASEID", length = 32)
	public String getCaseid() {
		return this.caseid;
	}

	public void setCaseid(String caseid) {
		this.caseid = caseid;
	}

	@Column(name = "TRIALTYPE", length = 2)
	public String getTrialtype() {
		return this.trialtype;
	}

	public void setTrialtype(String trialtype) {
		this.trialtype = trialtype;
	}

	@Column(name = "HTYPE", length = 2)
	public String getHtype() {
		return this.htype;
	}

	public void setHtype(String htype) {
		this.htype = htype;
	}

	@Column(name = "MODERATOR", length = 100)
	public String getModerator() {
		return this.moderator;
	}

	public void setModerator(String moderator) {
		this.moderator = moderator;
	}

	@Column(name = "TRIALTIME", length = 30)
	public String getTrialtime() {
		return this.trialtime;
	}

	public void setTrialtime(String trialtime) {
		this.trialtime = trialtime;
	}

	@Column(name = "TRIALPLACE", length = 100)
	public String getTrialplace() {
		return this.trialplace;
	}

	public void setTrialplace(String trialplace) {
		this.trialplace = trialplace;
	}

	@Column(name = "RECORDER", length = 100)
	public String getRecorder() {
		return this.recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	@Column(name = "JOINER", length = 100)
	public String getJoiner() {
		return this.joiner;
	}

	public void setJoiner(String joiner) {
		this.joiner = joiner;
	}

	@Column(name = "MATTERS", length = 500)
	public String getMatters() {
		return this.matters;
	}

	public void setMatters(String matters) {
		this.matters = matters;
	}

	@Column(name = "CONTENTS", length = 2000)
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "ANNEX", length = 100)
	public String getAnnex() {
		return this.annex;
	}

	public void setAnnex(String annex) {
		this.annex = annex;
	}

	@Column(name = "OPERATOR", length = 30)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPTTIME", length = 30)
	public String getOpttime() {
		return this.opttime;
	}

	public void setOpttime(String opttime) {
		this.opttime = opttime;
	}

	@Column(name = "TRIALMAN", length = 900)
	public String getTrialman() {
		return trialman;
	}

	@Column(name = "USERID", length = 19)
	public BigDecimal getUserid() {
		return userid;
	}

	public void setTrialman(String trialman) {
		this.trialman = trialman;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}
}
