package com.wfzcx.aros.wyInfoManage.po;
// Generated 2016-9-20 17:19:28 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Formula;
import org.hibernate.annotations.GenericGenerator;

/**
 * BContentbaseinfo generated by hbm2java
 */
@Entity
@Table(name = "B_CONTENTBASEINFO")
public class BContentbaseinfo implements java.io.Serializable {

	private String conid;
	private String title;
	private String content;
	private String opttime;
	private String operator;
	private String status;
	private String contype;
	private String receiveusername;
	private String receiveuserid;
	private String annex;
	private String releasetime;
	private String newssources;
	private String newsauthor;
	private String type;

	public BContentbaseinfo() {
	}

	public BContentbaseinfo(String conid) {
		this.conid = conid;
	}

	public BContentbaseinfo(String conid, String title, String content, String opttime, String operator, String status,
			String contype, String annex,String releasetime,String newssources,String newsauthor, String type) {
		this.conid = conid;
		this.title = title;
		this.content = content;
		this.opttime = opttime;
		this.operator = operator;
		this.status = status;
		this.contype = contype;
		this.annex = annex;
		this.releasetime=releasetime;
		this.newssources=newssources;
		this.newsauthor=newsauthor;
		this.type = type;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")	
	@Column(name = "CONID", unique = true, nullable = false, length = 32)
	public String getConid() {
		return this.conid;
	}

	public void setConid(String conid) {
		this.conid = conid;
	}

	@Column(name = "TITLE", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CONTENT", nullable = true)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "OPTTIME", length = 30)
	public String getOpttime() {
		return this.opttime;
	}

	public void setOpttime(String opttime) {
		this.opttime = opttime;
	}

	@Column(name = "OPERATOR", length = 30)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CONTYPE", length = 2)
	public String getContype() {
		return this.contype;
	}

	public void setContype(String contype) {
		this.contype = contype;
	}

	@Formula("(select replace(WMSYS.WM_CONCAT(u.username),',',',') from sys_user u, b_contentuserrelainfo b where u.userid = b.userid and b.conid=conid)")
	public String getReceiveusername() {
		return receiveusername;
	}

	public void setReceiveusername(String receiveusername) {
		this.receiveusername = receiveusername;
	}

	@Formula("(select replace(WMSYS.WM_CONCAT(u.userid),',',',') from sys_user u, b_contentuserrelainfo b where u.userid = b.userid and b.conid=conid)")
	public String getReceiveuserid() {
		return receiveuserid;
	}

	public void setReceiveuserid(String receiveuserid) {
		this.receiveuserid = receiveuserid;
	}
	
	@Column(name = "ANNEX", length = 100)
	public String getAnnex() {
		return annex;
	}

	public void setAnnex(String annex) {
		this.annex = annex;
	}

	@Column(name = "RELEASETIME", length = 30)
	public String getReleasetime() {
		return releasetime;
	}

	public void setReleasetime(String releasetime) {
		this.releasetime = releasetime;
	}

	@Column(name = "NEWSSOURCES", length = 50)
	public String getNewssources() {
		return newssources;
	}

	public void setNewssources(String newssources) {
		this.newssources = newssources;
	}

	@Column(name = "NEWSAUTHOR", length = 30)
	public String getNewsauthor() {
		return newsauthor;
	}

	public void setNewsauthor(String newsauthor) {
		this.newsauthor = newsauthor;
	}

	@Column(name = "TYPE", length = 2)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	
}
