[{  "rsId":1,
				"icon":"f:mdi-device-wifi-lock",
				"rsName":"ip权限设置",
				"childrens":[{
					"rsId":11,
					"icon":"f:mdi-hardware-security",
					"rsName":"IP限制",
					"childrens":[{
									"rsId":111,
									"icon":"f:mdi-action-verified-user",
									"rsName":"ip白名单",
									 "moduleUrl":"ipRestrictList.do?allow=true"
								},
								{
									"rsId":112,
									"icon":"f:mdi-notification-do-not-disturb",
									"rsName":"ip黑名单",
									"moduleUrl":"ipRestrictList.do?allow=false"
								}
					]
				},{
					"rsId":12,
					"icon":"f:mdi-action-lock",
					"rsName":"IP绑定",
					"childrens":[{
									"rsId":121,
									"icon":"f:mdi-image-camera-rear",
									"rsName":"绑定应用",
									"moduleUrl":"ipBoundList.do?userBound=false"
								},
								{
									"rsId":122,
									"icon":"f:mdi-image-camera-front",
									"rsName":"绑定用户",
									"moduleUrl":"ipBoundList.do?userBound=true"
								}
					]
				}]
			},{  "rsId":2,
				"icon":"f:mdi-device-wifi-lock",
				"rsName":"系统状态",
				"childrens":[{
					"rsId":21,
					"icon":"f:icon-chart",
					"rsName":"系统状态",
					"childrens":[{
									"rsId":211,
									"icon":"f:mdi-action-verified-user",
									"rsName":"在线用户",
									 "moduleUrl":"ipRestrictList.do?allow=true"
								},
								{
									"rsId":212,
									"icon":"f:mdi-notification-do-not-disturb",
									"rsName":"系统使用率",
									"moduleUrl":"ipRestrictList.do?allow=false"
								}
					]
				}]}]