package com.wfzcx.aros.gzgl.po;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * BRulebaseinfo generated by hbm2java
 */
@Entity
@Table(name = "B_RULEBASEINFO")
public class BRulebaseinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String ruleid;
	private String rulename;
	private String tabcode;
	private String tabname;
	private String fieldcode;
	private String fieldname;
	private String status;
	private String frequency;
	private BigDecimal limit;
	private String wherestr;
	private String operator;
	private String opttime;

	public BRulebaseinfo() {
	}

	public BRulebaseinfo(String ruleid) {
		this.ruleid = ruleid;
	}

	public BRulebaseinfo(String ruleid, String rulename, String tabcode,
			String tabname, String fieldcode, String fieldname, String status,
			String frequency, BigDecimal limit, String wherestr,
			String operator, String opttime) {
		this.ruleid = ruleid;
		this.rulename = rulename;
		this.tabcode = tabcode;
		this.tabname = tabname;
		this.fieldcode = fieldcode;
		this.fieldname = fieldname;
		this.status = status;
		this.frequency = frequency;
		this.limit = limit;
		this.wherestr = wherestr;
		this.operator = operator;
		this.opttime = opttime;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "RULEID")
	public String getRuleid() {
		return this.ruleid;
	}

	public void setRuleid(String ruleid) {
		this.ruleid = ruleid;
	}

	@Column(name = "RULENAME", length = 100)
	public String getRulename() {
		return this.rulename;
	}

	public void setRulename(String rulename) {
		this.rulename = rulename;
	}

	@Column(name = "TABCODE", length = 50)
	public String getTabcode() {
		return this.tabcode;
	}

	public void setTabcode(String tabcode) {
		this.tabcode = tabcode;
	}

	@Column(name = "TABNAME", length = 100)
	public String getTabname() {
		return this.tabname;
	}

	public void setTabname(String tabname) {
		this.tabname = tabname;
	}

	@Column(name = "FIELDCODE", length = 50)
	public String getFieldcode() {
		return this.fieldcode;
	}

	public void setFieldcode(String fieldcode) {
		this.fieldcode = fieldcode;
	}

	@Column(name = "FIELDNAME", length = 100)
	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "FREQUENCY", length = 2)
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "LIMIT", precision = 22, scale = 0)
	public BigDecimal getLimit() {
		return this.limit;
	}

	public void setLimit(BigDecimal limit) {
		this.limit = limit;
	}

	@Column(name = "WHERESTR", length = 500)
	public String getWherestr() {
		return this.wherestr;
	}

	public void setWherestr(String wherestr) {
		this.wherestr = wherestr;
	}

	@Column(name = "OPERATOR", length = 30)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "OPTTIME", length = 30)
	public String getOpttime() {
		return this.opttime;
	}

	public void setOpttime(String opttime) {
		this.opttime = opttime;
	}

}
